version: 2.1
orbs:
  slack: circleci/slack@4
jobs:
  lint:
    docker:
      - image: cimg/go:1.17
    steps:
      - checkout
      - run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.44.0
      - run: make lint
      - store_test_results:
          path: test-results

  test:
    docker:
      - image: cimg/go:1.17
    steps:
      - checkout
      - run: make test
      - store_test_results:
          path: test-results
      - slack/notify-on-failure:
          branch_pattern: main
          event: fail

workflows:
  version: 2
  build:
    jobs:
      - slack/notify-on-tag:
          filters:
            tags:
              only: /^v.*/
      - lint
      - test
