name: goreleaser

env:
  WORKING_DIRECTORY: .

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          cache-dependency-path: ${{env.WORKING_DIRECTORY}}/go.sum
          go-version-file: ${{env.WORKING_DIRECTORY}}/go.mod

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --clean
          workdir: ${{env.WORKING_DIRECTORY}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
