name: goreleaser

env:
  WORKING_DIRECTORY: .

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup dependencies
        uses: actions/setup-go@v4
        with:
          cache-dependency-path: ${{env.WORKING_DIRECTORY}}/go.sum
          go-version-file: ${{env.WORKING_DIRECTORY}}/go.mod

      - name: release publish
        run: make release GITHUB_TOKEN=${{secrets.GITHUB_TOKEN}}
